stream {
    server {
        listen 8100-8131;
        proxy_pass 100.101.105.127:$server_port;
        proxy_connect_timeout 5s;
        proxy_timeout 300s;
    }
    server {
        listen 9001-9032;
        proxy_pass 100.101.105.127:$server_port;
        proxy_connect_timeout 5s;
        proxy_timeout 300s;
    }
    server {
        listen 9200-9231;
        proxy_pass 100.101.105.127:$server_port;
        proxy_connect_timeout 5s;
        proxy_timeout 300s;
    }
}
